In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [19]:
date = 'Sept27th-'
filename = ''.join((date,'scan_stats.json'))
filename_SPADE = ''.join((date,'scan_stats_SPADE.json'))
filename, filename_SPADE

('Sept27th-scan_stats.json', 'Sept27th-scan_stats_SPADE.json')

In [21]:
df = pd.read_json(filename)

In [22]:
df

,M,N,D,T,num_SM_events,SM_total_spikes,noise,window_time,cluster_time,sequence_time,total_time,total_spikes,total_patterns,SM_acc
0,1,40,51,1000,8,10,100,0.013877,0.350059,0.000992,0.375947,180,5,[1.0]
1,4,40,51,1000,8,10,100,0.045851,0.541261,0.001030,0.698473,420,12,"[1.0, 1.0, 1.0, 1.0]"
2,8,40,51,1000,8,10,100,0.127068,0.778760,0.002983,1.222065,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
3,16,40,51,1000,8,10,100,0.470291,1.194564,0.002031,3.367971,1379,20,"[1.0, 1.0, 0.769230769230769, 1.0, 1.0, 1.0, 1..."
4,32,40,51,1000,8,10,100,2.970226,2.784409,0.001024,5.858682,2655,1,"[0.030303030303030002, 0.030303030303030002, 0..."
5,8,10,51,1000,8,10,100,0.244123,0.703348,0.003499,1.207376,739,13,"[1.0, 0.2, 0.769230769230769, 0.625, 1.0, 1.0,..."
6,8,20,51,1000,8,10,100,0.173422,0.746887,0.001959,1.240641,738,24,"[1.0, 0.6666666666666661, 1.0, 1.0, 1.0, 1.0, ..."
7,8,40,51,1000,8,10,100,0.153781,0.885747,0.002403,1.465257,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
8,8,80,51,1000,8,10,100,0.141834,1.306706,0.003680,2.114817,740,22,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
9,8,120,51,1000,8,10,100,0.116782,1.285266,0.001995,2.263749,740,21,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
10,8,40,11,1000,8,10,100,0.063131,1.034625,0.007425,1.295377,739,24,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
11,8,40,31,1000,8,10,100,0.098727,0.969140,0.001918,1.338961,739,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
12,8,40,51,1000,8,10,100,0.140607,1.066249,0.003027,1.641386,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
13,8,40,71,1000,8,10,100,0.248640,0.905129,0.002996,1.841817,739,18,"[1.0, 0.35000000000000003, 0.833333333333333, ..."
14,8,40,101,1000,8,10,100,0.271443,0.951734,0.002992,2.685786,740,23,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1]"
15,8,40,51,1000,2,10,100,0.020944,0.566091,0.000934,0.593953,260,1,"[0.0, 0.0, 0.0, 0.0, 0.1, 0.2, 0.1, 0.0]"
16,8,40,51,1000,4,10,100,0.041907,0.641873,0.000998,0.778512,420,8,"[1.0, 1.0, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0]"
17,8,40,51,1000,8,10,100,0.193243,0.961049,0.004039,1.510240,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
18,8,40,51,1000,16,10,100,0.615403,1.472384,0.001995,3.832536,1378,11,"[0.6666666666666661, 1.0, 0.13636363636363602,..."
19,8,40,51,1000,32,10,100,3.956639,3.147767,0.003572,15.974229,2653,12,"[0.208333333333333, 1.0, 0.204081632653061, 0...."
20,8,40,51,1000,8,3,100,0.027739,0.481204,0.000000,0.529916,292,1,"[0.0, 0.33333333333333304, 0.0, 0.0, 0.3333333..."
21,8,40,51,1000,8,5,100,0.042949,0.669609,0.000998,0.821419,420,6,"[1.0, 0.2, 0.2, 1.0, 0.2, 1.0, 1.0, 1.0]"
22,8,40,51,1000,8,10,100,0.159761,0.908766,0.002997,1.441181,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
23,8,40,51,1000,8,20,100,0.707382,1.641065,0.008799,4.618866,1377,49,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
24,8,40,51,1000,8,50,100,6.041500,3.726298,0.038122,28.958817,3283,118,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
25,8,40,51,1000,8,10,0,0.120452,0.853086,0.001993,1.506485,640,24,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
26,8,40,51,1000,8,10,50,0.131648,0.911443,0.002891,1.565630,690,25,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
27,8,40,51,1000,8,10,100,0.156514,1.018211,0.002991,1.577163,740,19,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
28,8,40,51,1000,8,10,500,0.366797,1.232117,0.000997,2.374850,1140,7,"[1.0, 0.1, 0.1, 1.0, 1.0, 0.1, 1.0, 1.0]"
29,8,40,51,1000,8,10,1000,0.820789,1.773808,0.001247,3.021672,1640,4,"[1.0, 0.1, 0.1, 0.1, 0.1, 1.0, 0.1, 1.0]"

In [24]:
df_SPADE = pd.read_json(filename_SPADE)
df_SPADE

,idx,M,N,D,T,num_SM_events,SM_total_spikes,noise,window_time,cluster_time,sequence_time,total_time,total_spikes,total_patterns,SM_acc
0,0,1,40,51,1000,8,10,100,NaT,NaT,NaT,0.134927,180,14.0,[1.0]
1,1,4,40,51,1000,8,10,100,NaT,NaT,NaT,2.193173,420,359.0,"[1.0, 1.0, 1.0, 1.0]"
2,2,8,40,51,1000,8,10,100,NaT,NaT,NaT,26.785469,740,2798.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
3,3,16,40,51,1000,8,10,100,NaT,NaT,NaT,450.879666,1379,21656.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
4,4,32,40,51,1000,8,10,100,NaT,NaT,NaT,NaN,2655,NaN,[None]
5,5,8,10,51,1000,8,10,100,NaT,NaT,NaT,87.592120,739,28089.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
6,6,8,20,51,1000,8,10,100,NaT,NaT,NaT,38.948132,738,7592.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
7,7,8,40,51,1000,8,10,100,NaT,NaT,NaT,28.704779,740,2798.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
8,8,8,80,51,1000,8,10,100,NaT,NaT,NaT,15.124313,740,785.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
9,9,8,120,51,1000,8,10,100,NaT,NaT,NaT,16.163250,740,533.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
10,10,8,40,11,1000,8,10,100,NaT,NaT,NaT,4.769448,739,582.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
11,11,8,40,31,1000,8,10,100,NaT,NaT,NaT,14.152079,739,1577.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
12,12,8,40,51,1000,8,10,100,NaT,NaT,NaT,28.817580,740,2798.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
13,13,8,40,71,1000,8,10,100,NaT,NaT,NaT,36.701559,739,3324.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
14,14,8,40,101,1000,8,10,100,NaT,NaT,NaT,45.435733,740,3828.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
15,15,8,40,51,1000,2,10,100,NaT,NaT,NaT,0.926268,260,78.0,"[1.0, 0.9090909090909091, 1.0, 1.0, 1.0, 1.0, ..."
16,16,8,40,51,1000,4,10,100,NaT,NaT,NaT,3.919321,420,392.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
17,17,8,40,51,1000,8,10,100,NaT,NaT,NaT,27.228813,740,2798.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
18,18,8,40,51,1000,16,10,100,NaT,NaT,NaT,349.560900,1378,28001.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
19,19,8,40,51,1000,32,10,100,NaT,NaT,NaT,NaN,2653,NaN,[None]
20,20,8,40,51,1000,8,3,100,NaT,NaT,NaT,1.151335,292,145.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
21,21,8,40,51,1000,8,5,100,NaT,NaT,NaT,3.839275,420,347.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
22,22,8,40,51,1000,8,10,100,NaT,NaT,NaT,29.367985,740,2798.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"

In [9]:
x = df['SM_acc'].tolist()
len(x)

10

In [18]:
df.loc(columns=['SM_acc','M'])

TypeError: _LocationIndexer.__call__() got an unexpected keyword argument 'columns'

In [11]:
for k in x:
    print(np.mean(k))

1.0
1.0
1.0
0.8568762651821862
0.04924242424242385
0.8242788461538462
0.9583333333333333
1.0
1.0
1.0